# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
            Snapcart\APIBundle\Entity\User: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_provider:
            entity:
                class: SnapcartAPIBundle:User
                property: username

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users, roles: IS_AUTHENTICATED_FULLY }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        users:
            pattern: ^/users
            stateless: true
            guard:
                entry_point: lexik_jwt_authentication.jwt_token_authenticator
                authenticators:
                    - snapcart.token_authenticator
                    - lexik_jwt_authentication.jwt_token_authenticator

#        main:
#            anonymous: ~
#            form_login:
#                login_path: login
#                check_path: login
#            provider: user_provider
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
