services:
#    snapcart_api.example:
#        class: Snapcart\APIBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    snapcart.user_service:
        class: Snapcart\APIBundle\Services\UserService
        arguments: ["@doctrine", "@security.password_encoder"]
    snapcart.token_authenticator:
        class: Snapcart\APIBundle\Security\TokenAuthenticator
        arguments: ["@service_container"]
    snapcart.auth.success_handler:
        class: Snapcart\APIBundle\Listener\AuthenticationSuccessHandler
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onJWTCreated}