<?php

namespace Snapcart\APIBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getListOfUsers($token, $sortBy, $sortDir, $userFilter, $createdType, $createdFilter)
    {
        $createdQuery = 'u.createdAt <= :createdAt';

        if($createdType == 'GT')
            $createdQuery = 'u.createdAt >= :createdAt';

        $q = $this
            ->createQueryBuilder('u')
            ->select('u.username, u.location, u.createdAt')
            ->where('u.accessToken != :accessToken OR u.accessToken is null')
            ->andWhere('u.username LIKE :userFilter')
            ->andWhere($createdQuery)
            ->setParameters([
                'accessToken' => $token,
                'userFilter' => '%'.$userFilter.'%',
                'createdAt' => $createdFilter->format('Y-m-d 23:59:59')
            ])
            ->orderBy('u.'.$sortBy, $sortDir);
        $users = $q->getQuery()->getResult();

        return $users;
    }
    public function getUserFromToken($token)
    {
        $user = $this->findOneBy([ 'accessToken' => $token ]);
        return $user;
    }
}
